"""heal_ruleset — build the in-guest heal_reflex ruleset from the brain's config.

The in-guest healer (heal_reflex) needs a self-contained JSON ruleset: where the
group HP/mana pixels are, and which KEYS to press. Historically that file carried
a hand-copied keymap that drifted from the brain's real binds (the dino macros:
"Alt#1,4" targeted a BUFF key and "3" was a DEBUFF, not a heal) -> it pressed
garbage and never healed. The fix: DERIVE the ruleset from the same two configs
the brain already owns, so the keys can't drift:

  - calibration.yaml -> group_bars / power_bar geometry -> the pixel locations
  - the active profile (ability_map) -> abilities[*].key + group_target_keys +
    tank_slot -> the action macros ("F2,4" = target tank then direct-heal)

Targeting is via group_target_keys (F1..F6), NOT the dino Alt-keys. Higher-tier
heals that aren't learned yet (key unset, learned:false, or "not learned" in the
desc) fall back to the standard heal so a critical member still gets healed.

Pure stdlib so it imports anywhere; the CLI reads YAML (PyYAML) and emits JSON.
"""
from __future__ import annotations

import json

# Bar fill colors + the chat-input region. Verified against a full-res guest frame
# (2026-06-17). Greens are the HP bar (full + slightly-dimmed), blue the power bar.
GREEN = [0, 255, 0]
GREEN_ALT = [0, 222, 0]
BLUE = [113, 113, 240]
CHAT_INPUT_REGION = {"x": 50, "y": 1019, "w": 208, "h": 22}   # from agent.guest_sense.CHAT_INPUT
CHAT_BRIGHT_THRESHOLD = 25

# Where along each bar to sample (fraction of the track, left=0 right=1). HP bars
# deplete right->left, so a higher fraction trips at higher HP. ALIGNED to the brain's
# thresholds.yaml: std 0.90 (heal below 90% HP), cri 0.75 (bigger heal below 75%).
# mana ~0.24 = "don't std-heal under ~24% power".
STD_FRAC = 0.90
CRI_FRAC = 0.75
MANA_FRAC = 0.24


def _usable(ab: dict | None) -> bool:
    """A heal ability is castable now: key set, not 'none', and not flagged
    unlearned (learned:false or a 'not learned' note in the desc)."""
    if not ab:
        return False
    key = str(ab.get("key") or "").strip()
    if not key or key.lower() == "none":
        return False
    if ab.get("learned") is False:
        return False
    if "not learned" in str(ab.get("desc") or "").lower():
        return False
    return True


def build_heal_ruleset(calibration: dict, ability_map: dict) -> dict:
    cal = calibration or {}
    am = ability_map or {}
    gb = cal.get("group_bars", {}) or {}
    x0 = int(gb.get("x0", 33)); x1 = int(gb.get("x1", 139))
    hp_y = int(gb.get("hp_base_y", 120)); pitch = int(gb.get("pitch", 75))
    slots = int(gb.get("slots", 6))
    pwr = cal.get("power_bar", {}) or {}
    px0 = int(pwr.get("x0", 19)); px1 = int(pwr.get("x1", 128)); pwy = int(pwr.get("y", 46))

    abil = am.get("abilities", {}) or {}
    gtk = am.get("group_target_keys") or ["F1", "F2", "F3", "F4", "F5", "F6"]

    def tgt(i: int) -> str:
        return gtk[i] if i < len(gtk) else f"F{i + 1}"

    std_key = str((abil.get("direct_heal") or {}).get("key") or "4")
    crit_ab = abil.get("critical_heal") or {}
    crit_key = str(crit_ab.get("key")) if _usable(crit_ab) else std_key
    grp_ab = abil.get("group_heal") or {}
    grp_key = str(grp_ab.get("key")) if _usable(grp_ab) else std_key
    cure_ab = abil.get("cure") or {}
    cure_key = str(cure_ab.get("key")) if _usable(cure_ab) else None

    std_x = round(x0 + STD_FRAC * (x1 - x0))
    cri_x = round(x0 + CRI_FRAC * (x1 - x0))
    mana_x = round(px0 + MANA_FRAC * (px1 - px0))

    standard, critical, group_check = {}, {}, {}
    for i in range(slots):
        y = hp_y + pitch * i
        standard[str(i)] = {"action": f"heal_{i}_std", "loc": [std_x, y], "clr": GREEN, "alt_clr": GREEN_ALT}
        critical[str(i)] = {"action": f"heal_{i}_cri", "loc": [cri_x, y], "clr": GREEN, "alt_clr": GREEN_ALT}
        # presence: HP-row left edge is green when a member is present, black when empty
        group_check[str(i)] = {"loc": [x0, y], "clr": [0, 0, 0]}

    actions: dict[str, dict] = {}
    for i in range(slots):
        actions[f"heal_{i}_std"] = {"action": f"{tgt(i)},{std_key}"}
        actions[f"heal_{i}_cri"] = {"action": f"{tgt(i)},{crit_key}"}
    actions["heal_group_std"] = {"action": grp_key}
    actions["heal_group_cri"] = {"action": grp_key}
    # Jenskin has ONE generic cure key (any type) -> nox/ele/tra all map to it.
    # Emitted for completeness; cures stay INERT until the detriment-cell pixels
    # are calibrated and added to standard[i].nox/ele/tra (omitted here on purpose).
    if cure_key:
        for i in range(min(3, slots)):
            for base in ("cure_nox", "cure_ele", "cure_tra"):
                actions[f"{base}_{i}"] = {"action": f"{tgt(i)},{cure_key}"}

    return {
        "_README": "GENERATED by guest_agent/heal_ruleset.py from calibration.yaml + the "
                   "active profile's ability_map. Do NOT hand-edit keys here — change them in "
                   "the profile and re-run the sync. Pixels come from group_bars/power_bar.",
        "tick": 0.1,
        "tol": 14,
        "cure_present_clr": [0, 0, 0],
        "game_present": {"region": {"x": px0, "y": pwy - 2, "w": px1 - px0, "h": 6},
                         "blue": BLUE, "tolerance": 40, "min_pixels": 20},
        "chat_input": {"region": dict(CHAT_INPUT_REGION), "bright_threshold": CHAT_BRIGHT_THRESHOLD},
        "pixels": {
            "self_mana": {"loc": [mana_x, pwy], "clr": BLUE},
            "group_check": group_check,
            "standard": standard,
            "critical": critical,
        },
        "actions": actions,
    }


def _load_yaml(path: str) -> dict:
    import yaml  # PyYAML; present in the brain's env
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


def main(argv: list[str] | None = None) -> int:
    import argparse
    import os
    from pathlib import Path

    ap = argparse.ArgumentParser(description="Build the in-guest heal_reflex ruleset (JSON to stdout).")
    ap.add_argument("--config-dir", default=os.environ.get("IB_CONFIG_DIR"),
                    help="dir holding calibration.yaml + active_profile + profiles/ (default $IB_CONFIG_DIR)")
    ap.add_argument("--calibration", help="explicit calibration.yaml path")
    ap.add_argument("--profile", help="explicit profile yaml path (overrides active_profile)")
    a = ap.parse_args(argv)

    cd = Path(a.config_dir) if a.config_dir else None
    cal_path = a.calibration or (cd / "calibration.yaml" if cd else None)
    if a.profile:
        prof_path = a.profile
    elif cd:
        active = (cd / "active_profile").read_text(encoding="utf-8").strip()
        prof_path = cd / "profiles" / f"{active}.yaml"
    else:
        prof_path = None
    if not cal_path or not prof_path:
        ap.error("need --config-dir or both --calibration and --profile")

    ruleset = build_heal_ruleset(_load_yaml(str(cal_path)), _load_yaml(str(prof_path)))
    print(json.dumps(ruleset, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
